name: Android CI/CD

on:
  push:
    branches: [ dev ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload to App Center
        env:
          APPCENTER_TOKEN: ${{ secrets.APPCENTER_TOKEN }}
        run: |
          appcenter distribute release \
            --app "TU_ORG/TU_APP" \
            --group "Testers" \
            --file app/build/outputs/apk/debug/app-debug.apk \
            --release-notes "Build from GitHub Actions"
